A<-read.delim("combinedpost.sort.tsv",sep="|",header=F)
library(ggplot2)
pdf("combinedpost.sort.barplot.pdf")
ggplot(data=A[1:20,],aes(y=V2,x=reorder(V1,V2)))+geom_bar(stat="identity")+coord_flip()+ylab("Post count")+xlab("Name")+theme_light()
dev.off()
B<-read.delim("words.sort.tsv",sep="|",header=F)
pdf("words.sort.barplot.pdf")
ggplot(data=B[1:20,],aes(y=V2,x=reorder(V1,V2)))+geom_bar(stat="identity")+coord_flip()+ylab("Wordcount")+xlab("Name")+theme_light()
dev.off()
